### ISSUE TITLE
How do you find the store application id of apps?

### ISSUE THREAD

**Issue by leglock** [dmix90/StoreAppLauncher#2]
Sorry to post this as a issue, but couldn't find any other way to contact you.

I was able to add Killer Instinct using the example application id you provided as the parameter and it works well. I am trying to add a few more games (Hydro Thunder, Gears of War) but can't for the life of me figure out where to find those application id's.

The folder names in C:\Program Files\WindowsApps look similar, but Killer Instincts id is slightly different from the folder name and I can't quite figure out any pattern to that difference. I also tried looking at the AppxManifest.xml file but dind't see anything in there that looked like it.

How can I find out the application id for other installed apps on my own to use with the launcher?

**Comment by dougheater** [comment]
Hey. Sorry for late reply. Just noticed this...

How to find Application ID:
1. Launch Go to Applications Folder link from archive you downloaded( or Win + R -> shell:AppsFolder -> Enter ) .
2. Press the F10 key on the keyboard. The window will get a menu, click View -> Choose Details.
3. In the next dialog, tick the AppUserModelId checkbox.
4. Switch folder view mode to "Details".
5. Find application you need and look at AppUserModelID column it will show ID you looking for.
6. Enter this id as a parameter to StoreAppLauncher_xXX.exe

Also there is a way to get ids from code. But i havent digged much in that direction.
