### ISSUE TITLE
Missing VCRuntime140.dll and MSVCP140.dll for x64 version

### ISSUE THREAD

**Issue by churchymayer** [dmix90/StoreAppLauncher#3]
When I try to start the x64 version of the Launcher I get a message that VCRUNTIME140.dll and MSVCP140.dll are missing. The x86 version is working fine.

**Comment by dougheater** [comment]
Try to install Microsoft Visual C++ 2015 Redistributable, both x64 and x86.

**Comment by churchymayer** [comment]
OK, that worked, thanks for the help :)
